---
# Install base packages

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true 
    upgrade: safe
    autoremove: true
    cache_valid_time: 3600

- name: Install base packages
  ansible.builtin.apt:
    name:
    - alacritty
    - ansible
    - build-essential
    - curl
    - fd-find
    - git
    - htop
    - nnn
    - npm
    - ripgrep
    - unzip
    - wl-clipboard
    - zsh
    state: present
    autoremove: true
    purge: true

- name: Install development packages needed in compile Ruby
  ansible.builtin.apt:
    name:
    - autoconf
    - patch
    - build-essential
    - rustc
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libgmp-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm6
    - libgdbm-dev
    - libdb-dev
    - uuid-dev
    state: present
    autoremove: true
    purge: true

- name: Remove some default packages
  ansible.builtin.apt:
    name:
    - evolution
    - transmission-gtk
    state: absent
    autoremove: true
    purge: true

- name: Make sure we have a 'sudo' group
  ansible.builtin.group:
    name: sudo
    state: present

- name: Add the users to the 'sudo' group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: sudo
    append: yes

- name: Get zsh path
  ansible.builtin.command: which zsh 
  register: zsh_path
  when: not ansible_user_shell is search("zsh")
  changed_when: false

- name: Switch to zsh
  ansible.builtin.user:
    name: "{{ user }}"
    shell: "{{ zsh_path.stdout }}"
  when: not ansible_user_shell is search("zsh")

- name: Ensure /etc/samba directory exists
  ansible.builtin.file:
    path: /etc/samba
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Ensure /etc/samba/smb.conf has the correct content
  ansible.builtin.copy:
    dest: /etc/samba/smb.conf
    content: |
      [global]
      client min protocol = SMB2
      client max protocol = SMB3
    owner: root
    group: root
    mode: '0644'

- name: Disable SMBv1 for libsmbclient
  ansible.builtin.copy:
    dest: /etc/samba/smb.conf
    content: |
      [global]
      client min protocol = SMB2
      client max protocol = SMB3
    owner: root
    group: root
    mode: '0644'

