source $HOME/.zsh/history
source $HOME/.zsh/prompt
source $HOME/.zsh/bindings
source $HOME/.zsh/aliases

export PATH=$PATH:$HOME/.bin:$HOME/.bin-dl

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# asdf
. $HOME/.asdf/asdf.sh

# ruby
# export PATH=$HOME/.rbenv/bin:$PATH
# eval "$(rbenv init -)"

# go
# export GOPATH=$HOME/Code/go
# export PATH=/usr/local/go/bin:$GOPATH/bin:$PATH

# terraform
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /home/tb/.bin-dl/terraform terraform
