# uncomment to profile:
# zmodload zsh/zprof

source $HOME/.zsh/history
source $HOME/.zsh/prompt
source $HOME/.zsh/bindings
source $HOME/.zsh/aliases

export PATH=$PATH:$HOME/.bin:$HOME/.bin-dl:$HOME/.local/bin

# env for neovim
export PATH=$PATH:/opt/nvim/nvim-linux-x86_64/bin

# env for go
export GOPRIVATE="github.com/heroku/*,git.soma.salesforce.com/*"
export GOPATH=$HOME/Code/go
export PATH=$PATH:$GOPATH/bin

export EDITOR=nvim

# check for compinit cache regenerating once a day
autoload -Uz compinit
for dump in $HOME/.zcompdump(N.mh+24); do
  compinit
done
compinit -C

# mise
if which mise &> /dev/null; then
  eval "$(mise activate zsh)"
fi

# fzf
if which fzf &> /dev/null; then
  source <(fzf --zsh)
fi

# kubectl
if which kubectl &> /dev/null; then
  # enable completing on demand, cause it's slow:
  # https://github.com/kubernetes/kubernetes/issues/59078
  # https://github.com/kubernetes/kubernetes/pull/96087
  function ka() {
    source <(command kubectl completion zsh)
    complete -F __start_kubectl k
  }
fi

# terraform
if which terraform &> /dev/null; then
  autoload -U +X bashcompinit && bashcompinit
  complete -o nospace -C $(which terraform) terraform
fi

# rust
if [ -f $HOME/.cargo/env ]; then
. "$HOME/.cargo/env"
fi

# java
java_dir=/usr/lib/jvm/java-17-openjdk-amd64
if [ -d "$java_dir" ]; then
  export JAVA_HOME=$java_dir
  export PATH=$JAVA_HOME/bin:$PATH
fi

# maven
maven_dir=/usr/share/maven
if [ -d "$java_dir" ]; then
  export MAVEN_HOME=$java_dir
  export PATH=$MAVEN_HOME/bin:$PATH
fi

# pipx: add first in the path to use pipx version of system-wide binaries
export PATH="$HOME/.local/bin:$PATH"

# heroku stuff
cloud() {
  eval "$(ion-client shell)"
  cloud "$@"
}

# uncomment to profile:
# zprof

