---
- hosts: localhost
  gather_facts: true
  vars:
  - asdf_plugins:
    - golang
    - ruby
  - asdf_version: "v0.8.0"
  - dotfiles_tag: "linux-desktop"
  - tools:
    - chrome
    - fzf
    - kubectl
    - kube-ps1
    - nextcloud-client
    - nordvpn
    - signal
    - terraform
    - transmission-client
    - vscode
  roles:
  - laptop_base
  - dotfiles
  - asdf
  - tools
  - regolith
