---
docker_packages_to_remove:
  - docker.io
  - docker-doc
  - docker-compose
  - podman-docker
  - containerd
  - runc
docker_packages_to_install:
  - ca-certificates
  - curl
  - gnupg
docker_components_to_install:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
docker_apt_key_url: https://download.docker.com/linux/debian/gpg
docker_apt_key_path: /etc/apt/keyrings/docker.asc
docker_apt_repo_template: >-
  deb [arch={{ docker_architecture }} signed-by={{ docker_apt_key_path }}] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable


