---
- name: Ensure required tools are installed
  ansible.builtin.apt:
    name:
      - wget
      - coreutils
    state: present
    update_cache: true

- name: Download Filen .deb file
  ansible.builtin.get_url:
    url: "{{ filen_deb_url }}"
    dest: "{{ filen_deb_path }}"
    mode: '0644'

- name: Download checksum file
  ansible.builtin.uri:
    url: "{{ filen_checksum_url }}"
    return_content: true
  register: filen_checksum_file

- name: Extract expected SHA256 checksum
  ansible.builtin.set_fact:
    filen_expected_sha256: "{{ filen_checksum_file.content.split(' ')[0] | trim }}"

- name: Calculate actual SHA256 checksum
  ansible.builtin.command: sha256sum {{ filen_deb_path }}
  register: filen_actual_sha_output
  changed_when: false

- name: Fail if checksum does not match
  ansible.builtin.fail:
    msg: |
      SHA256 checksum does not match!
      Expected: {{ filen_expected_sha256 }}
      Actual:   {{ filen_actual_sha_output.stdout.split()[0] | trim }}
  when: filen_actual_sha_output.stdout.split()[0] | trim != filen_expected_sha256

- name: Install Filen desktop client
  ansible.builtin.apt:
    deb: "{{ filen_deb_path }}"
    state: present

- name: Remove .deb file
  ansible.builtin.file:
    path: "{{ filen_deb_path }}"
    state: absent

