#!/bin/bash

percentage=`acpi -b | gawk -F '[^0-9]*' '{ SUM += $3 } END { printf "%0.0f", SUM/2 }'`
full_text="$percentage%"
short_text=""

if [ $percentage -lt 20 ]
then
  color="#FF0000"
elif [ $percentage -lt 40 ]
then
  color="#FFAE00"
elif [ $percentage -lt 60 ]
then
  color="#FFF600"
elif [ $percentage -lt 85 ]
then
  color="#A8FF00"
fi

echo $full_text
echo $short_text
echo $color

case $BLOCK_BUTTON in
  1) details=`acpi -b`; notify-send "$details" ;; # lef click
esac
