#!/bin/bash

time=`date '+%b %d, %H:%M'`
full_text="$time"
short_text=""
color=""

echo $full_text
echo $short_text
echo $color

case $BLOCK_BUTTON in
  1) details=`cal -h`; notify-send "$details" ;; # lef click
esac
