#!/bin/bash

docker run --rm -it \
  -u $UID:$(id -g) \
  -v "$HOME/.cache/go-build:/home/user/.cache/go-build" \
  -v $GOPATH:/home/user/go \
  -v $PWD:/usr/src/myapp \
  -w /usr/src/myapp \
  tbalthazar/golang \
  go $@
