---

- name: Install required packages
  ansible.builtin.apt:
    name:
      - dconf-cli
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-manager
      - pipx
    state: present
    update_cache: yes

- name: Ensure pipx is initialized for the user
  become: false
  ansible.builtin.command: pipx ensurepath
  register: pipx_ensurepath
  changed_when: "'is already in PATH' not in pipx_ensurepath.stdout"

- name: Install gnome-extensions-cli via pipx
  become: false
  ansible.builtin.command: pipx install gnome-extensions-cli --system-site-packages
  register: pipx_gext
  changed_when: "'already installed' not in pipx_gext.stdout"
  failed_when: pipx_gext.rc != 0 and 'already installed' not in pipx_gext.stdout

- name: Install GNOME extensions with gext
  become: false
  ansible.builtin.shell: |
    ~/.local/bin/gext --filesystem install {{ item }}
  args:
    creates: "~/.local/share/gnome-shell/extensions/{{ item }}"
    executable: /bin/bash
  loop: "{{ gnome_extension_ids }}"

# Address https://gitlab.com/lundal/tactile/-/issues/44
- name: Compile GSettings schemas for GNOME extensions
  become: false
  ansible.builtin.command: glib-compile-schemas --strict schemas
  args:
    chdir: "~/.local/share/gnome-shell/extensions/{{ item }}"
    creates: "~/.local/share/gnome-shell/extensions/{{ item }}/schemas/gschemas.compiled"
  loop: "{{ gnome_extension_ids }}"

- name: Load tactile config into GNOME dconf
  become: false
  ansible.builtin.shell: |
    dconf load /org/gnome/shell/extensions/tactile/ < {{ tactile_config_path }}
  args:
    executable: /bin/bash
  vars:
    tactile_config_path: "{{ role_path }}/files/tactile.conf"
  changed_when: false

