---
- hosts: localhost
  gather_facts: true
  become: true
  vars:
    user: tb
    # TODO: revert to default branch
    dotfiles_branch: "tb/2025"
  roles:
  - base
  - dotfiles
  - gnome-tweaks
  - neovim
  - zellij
  - mise
  - flatpak
  - firefox
  - obsidian
  - vscode
  - filen
  - signal
  - proton-pass
  - proton-vpn
  # - virtualbox
