---
- hosts: localhost
  gather_facts: true
  become: true
  vars:
    user: tb
    # TODO: revert to default branch
    dotfiles_branch: "tb/2025"
    dotfiles_repo: "https://github.com/tbalthazar/dotfiles"
  roles:
  - base
  - fzf
  - dotfiles
  - neovim
  - zellij
  - mise
