---
- hosts: localhost
  gather_facts: true
  become: true
  vars:
    user: tb
    # TODO: revert to default branch
    dotfiles_branch: "tb/2025"
  roles:
  - fzf
  - neovim
  - zellij
  - obsidian
  - kube-ps1
  - filen
  - proton-pass
