---
# Install ProtonVPN

- name: Define .deb filename and URL
  ansible.builtin.set_fact:
    protonvpn_deb_url: "https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_{{ protonvpn_version }}_all.deb"
    protonvpn_deb_path: "/tmp/protonvpn_{{ protonvpn_version }}.deb"

- name: Download ProtonVPN .deb file
  ansible.builtin.get_url:
    url: "{{ protonvpn_deb_url }}"
    dest: "{{ protonvpn_deb_path }}"
    mode: '0644'
    force: true

- name: Check SHA256 of downloaded file
  ansible.builtin.command: "sha256sum {{ protonvpn_deb_path }}"
  register: protonvpn_sha_output
  changed_when: false

- name: Ensure SHA256 checksum matches
  ansible.builtin.assert:
    that:
      - protonvpn_sha_output.stdout.split()[0] == protonvpn_deb_sha256
    fail_msg: "SHA256 checksum does not match. Aborting install."
    success_msg: "SHA256 checksum matches."

- name: Install ProtonVPN .deb file (configure the repo)
  ansible.builtin.apt:
    deb: "{{ protonvpn_deb_path }}"
    state: present

- name: Delete downloaded .deb file
  ansible.builtin.file:
    path: "{{ protonvpn_deb_path }}"
    state: absent

- name: Install Proton VPN packages
  ansible.builtin.apt:
    name:
    - proton-vpn-gnome-desktop
    state: present
    autoremove: true
    purge: true
    update_cache: true
