#!/bin/bash

alias ls='ls -lh'
alias ping='ping -c4'
alias skill='sudo kill -9'
alias gs='git status'
alias gd='git difftool'
alias gc='git commit -a'
alias gls='git log --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr %an)%Creset" --abbrev-commit --date=relative'
alias gamend='git commit --amend --no-edit'
alias gsu='git branch --set-upstream-to=origin/`git symbolic-ref --short HEAD`'
alias glst='gls --graph'
alias gemi='gem install --no-rdoc --no-ri'
alias gemu='gem update --no-rdoc --no-ri'
alias gvim="gvim 2>/dev/null"
alias torbrowser="~/Downloads/tor-browser_en-US/start-tor-browser"
alias hosts="sudo vim /etc/hosts"
alias ctags_for_rails="ctags -R -f tags.ctags --exclude=.git --exclude=log/*"
alias upgradesystem='sudo apt-get update && sudo apt-get upgrade'
alias meteo='curl wttr.in'
alias hardware-network='sudo lshw -class network'
alias audio-volume='pactl set-sink-volume @DEFAULT_SINK@'
alias mic-volume='pactl set-source-volume @DEFAULT_SOURCE@'
alias connect-vpn='sudo /usr/sbin/openvpn --daemon ovpn --status /run/openvpn/openvpn.status 10 --cd /etc/openvpn --writepid /run/openvpn/home.pid --config /home/tb/Documents/perso/NordVPN/config/at3.nordvpn.com.tcp443.ovpn --auth-user-pass ~/.openvpn-auth'
alias home-usage='du -hx -d 1 -t 1G ~/ | sort -hr'
alias restartnm='sudo pkill NetworkManager && sleep 1 && sudo NetworkManager'
alias nsaudit='sudo netstat -plunt'
alias vdirsyncer='~/.vdirsyncer-env/bin/vdirsyncer'
alias be='bundle exec'
alias ber='bundle exec rails'
alias bers='bundle exec rspec'
alias cop='bundle exec rake coal_car:rubocop'
alias h='heroku'
alias cdh='cd ~/Code/heroku'
alias hisg='history | grep'
alias frt='foreman run ~/.bin/terraform'
alias gitb='hub browse'
alias rib='h run:inside web.1 bash -a'
alias rctags='ctags -f tags.ctags -R --languages=ruby --exclude=.git --exclude=log .'
