#!/bin/bash

usage() {
	echo -e "change-resolution\n\tThis script changes screen resolution in .Xresources.\n"
	echo "Usage:"
	echo "  change-resolution 96 - set the screen resolution to 96 dpi"
	echo "  change-resolution 192 - set the screen resolution to 96 dpi"
}

main() {
  dpi=$1
  if [[ -z "$dpi" ]]; then
    usage
    exit 1
  fi

  sed -i "s/^Xft.dpi: [[:digit:]]*$/Xft.dpi: $dpi/" ~/.Xresources
  xrdb ~/.Xresources 
}

main "$@"
