---
# Install Zellij

- name: Check installed version of Zellij
  become: false
  ansible.builtin.shell:
    cmd: "$HOME/.bin-dl/zellij --version | cut -d ' ' -f 2"
  register: zellij_installed_version
  failed_when: false
  changed_when: false

- name: Download Zellij
  become: false
  ansible.builtin.get_url:
    url: "https://github.com/zellij-org/zellij/releases/download/v{{ zellij_version }}/zellij-x86_64-unknown-linux-musl.tar.gz"
    dest: "/tmp/zellij-x86_64-unknown-linux-musl.tar.gz"
    force: true
    mode: 0644
  when: zellij_installed_version.stdout is not defined or not zellij_installed_version.stdout is search(zellij_version)

- name: Decompress Zellij
  become: false
  unarchive:
    src: "/tmp/zellij-x86_64-unknown-linux-musl.tar.gz"
    remote_src: yes
    dest: "/tmp"
  check_mode: false
  when: zellij_installed_version.stdout is not defined or not zellij_installed_version.stdout is search(zellij_version)

- name: Download Zellij Signature
  become: false
  ansible.builtin.get_url:
    url: "https://github.com/zellij-org/zellij/releases/download/v{{ zellij_version }}/zellij-x86_64-unknown-linux-musl.sha256sum"
    dest: "/tmp/zellij-x86_64-unknown-linux-musl.sha256sum"
    force: true
    mode: 0644
  when: zellij_installed_version.stdout is not defined or not zellij_installed_version.stdout is search(zellij_version)

- name: Verify file checksum
  become: false
  command: sha256sum --check /tmp/zellij-x86_64-unknown-linux-musl.sha256sum
  args:
    chdir: /tmp
  register: checksum_result
  failed_when: "'FAILED' in checksum_result.stdout"
  when: zellij_installed_version.stdout is not defined or not zellij_installed_version.stdout is search(zellij_version)

# - name: Show checksum verification result
#   debug:
#     var: checksum_result.stdout

- name: Remove old Zellij version
  become: false
  ansible.builtin.file:
    path: "$HOME/.bin-dl/zellij"
    state: absent
  when: zellij_installed_version.stdout is not defined or not zellij_installed_version.stdout is search(zellij_version)

- name: Create destination dir
  become: false
  ansible.builtin.file:
    path: "$HOME/.bin-dl"
    state: directory
  when: zellij_installed_version.stdout is not defined or not zellij_installed_version.stdout is search(zellij_version)

- name: Copy file to new location
  become: false
  ansible.builtin.copy:
    src: "/tmp/zellij"
    dest: "$HOME/.bin-dl/zellij"
    remote_src: yes
    mode: "0754"
  when: zellij_installed_version.stdout is not defined or not zellij_installed_version.stdout is search(zellij_version)

- name: Remove the old file
  become: false
  ansible.builtin.file:
    path: "/tmp/zellij"
    state: absent
  when: zellij_installed_version.stdout is not defined or not zellij_installed_version.stdout is search(zellij_version)
